version: '4'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    container_name: foodgram-back
    build: ./backend/
    env_file: .env
    volumes:
      - static:/app/static
      - media:/app/media/
    depends_on:
      - db
  frontend:
    container_name: foodgram-front
    build: ./frontend/
    command: cp -r /app/build/. /static/
    volumes:
      - static:/app/static
  nginx:
    container_name: foodgram-proxy
    build: ./nginx/
    ports:
      - 80:80
      - 8000:80
    depends_on:
      - backend
      - frontend
    volumes:
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static:/static
      - media:/media/


