version: '4'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: gevo10/foodgramm-backend
    env_file: .env
    volumes:
      - static:/app/static
      - media:/app/media/
    depends_on:
      - db
  frontend:
    image: gevo10/foodgramm-frontend 
    command: cp -r /app/build/. /static/
    volumes:
      - static:/app/static
  nginx:
    image: gevo10/foodgramm-proxy 
    ports:
      # - 80:80
      - 8000:80
    depends_on:
      - backend
      - frontend
    volumes:
      - static:/static
      - media:/media/
