version: '4'

volumes:
  # pg_data:
  static:
  media:

services:
  backend:
    container_name: foodgram-back
    build: ./backend/
    volumes:
      - static:/app/static
      - ./data:/app/data
      - media:/app/media/
  frontend:
    container_name: foodgram-front
    build: ./frontend/
    command: cp -r /app/build/. /static/
    volumes:
      - static:/app/static
  nginx:
    container_name: foodgram-proxy
    build: ./nginx/
    # image: nginx:1.25.4-alpine
    ports:
      - "80:80"
      - "8000:8000"
    depends_on:
      - backend
      - frontend
    volumes:
      # - ../nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      # - ../frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static:/static
      - media:/media/


