"""Основные константы."""

LENGTH_INGREDIENT_NAME = 128
LENGTH_INGREDIENT_MEAS_UNIT = 64
LENGTH_RECIPE_NAME = 256
LENGTH_TAGS_NAME = 32
LENGTH_TAGS_SLUG = 32
MIN_LIMIT_COOK_TIME = 1
MAX_LIMIT_COOK_TIME = 32767
MIN_LIMIT_AMOUNT = 1
MAX_LIMIT_AMOUNT = 32767
