# Generated by Django 3.2.3 on 2024-08-20 11:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientrecipe',
            name='amount',
            field=models.PositiveSmallIntegerField(help_text='Введите килество ингредиента', validators=[django.core.validators.MinValueValidator(limit_value=1, message='Укажите количество не меньше 1')], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(help_text='Время приготовление укажите в минутах', validators=[django.core.validators.MinValueValidator(limit_value=1, message='Укажите время не меньше 1 минуты')], verbose_name='Время приготовления в минутах'),
        ),
    ]
