# Generated by Django 3.2.3 on 2024-08-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20240815_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='top_recipes',
            field=models.TextField(blank=True, help_text='Перечислите свои любимые блюда', max_length=500, verbose_name='Топ любимых блюд'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Адрес электронной почты'),
        ),
    ]
