# Generated by Django 3.2.3 on 2024-09-10 08:33

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20240822_1439'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subscruser',
            constraint=models.CheckConstraint(check=models.Q(('author', django.db.models.expressions.F('subscriber')), _negated=True), name='No self sibscription'),
        ),
    ]
