# Generated by Django 3.2.3 on 2024-09-10 08:37

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_subscruser_no self sibscription'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscruser',
            name='No self sibscription',
        ),
        migrations.AddConstraint(
            model_name='subscruser',
            constraint=models.CheckConstraint(check=models.Q(('author', django.db.models.expressions.F('subscriber')), _negated=True), name='Нельзя подписаться на себя'),
        ),
    ]
