# Generated by Django 3.2.3 on 2024-09-10 08:58

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20240910_1137'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscruser',
            name='Нельзя подписаться на себя',
        ),
        migrations.AddConstraint(
            model_name='subscruser',
            constraint=models.CheckConstraint(check=models.Q(('author', django.db.models.expressions.F('subscriber'))), name='Нельзя подписаться на себя'),
        ),
    ]
