# Generated by Django 3.2.3 on 2024-09-10 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20240910_1158'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscruser',
            name='Нельзя подписаться на себя',
        ),
    ]
