# Generated by Django 3.2.3 on 2024-09-12 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_subscruser_нельзя подписаться на себя'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='avatar',
            field=models.ImageField(blank=True, help_text='загрузите вашу аватарку', null=True, upload_to='users/images/', verbose_name='Аватар'),
        ),
    ]
